### ISSUE TITLE
Remove SkipLast

### ISSUE THREAD

**Issue by iCodeSometime** [morelinq/MoreLINQ#811] opened 2021-03-23 21:45 UTC
MoreLinq is inconvenient to use when also using `SkipLast`, because Linq has it's own TakeLast method now.

Trying to compile gives an error 
```
The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.SkipLast<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)' and 'MoreLinq.MoreEnumerable.SkipLast<T>(System.Collections.Generic.IEnumerable<T>, int)'
```

**Comment by atifaziz** [comment] 2021-03-23 22:03
I'm closing this as a duplicate of #565 since it's in the same vein as the discussion happening there.

**Closed by atifaziz** 2021-03-23 22:03 UTC
Labels: duplicate
