### ISSUE TITLE
split function won't always return all item in the split collection

### ISSUE THREAD

**Issue by pilotMike** [morelinq/MoreLINQ#746] opened 2020-04-04 00:28 UTC
https://github.com/morelinq/MoreLINQ/blob/07bd0861658b381ce97c8b44d3b9f2cd3c9bf769/MoreLinq/Split.cs#L284

```
for example, take this code:
string s = "111122";
char first = s[0];
var partitions = s.Split(c => {
    bool flag = c != first;
    first = c;
    return flag;
}).ToList();
```

I might get something like `1111` and `2`.
Whereas I expect to see `1111` and `22`

This code will produce the correct splits:
```
var l = new List<T>();
foreach (var item in source)
{
	if (split(item))
	{
		yield return new List<T>(l);
		l.Clear();
	}
	l.Add(item);

}
yield return l;
```

**Comment by atifaziz** [comment] 2020-04-09 16:13
`Split` is not right here. You want to use [`Segment`](https://morelinq.github.io/3.3/ref/api/html/M_MoreLinq_MoreEnumerable_Segment__1.htm) instead.

`Segment` splits _between_ elements whereas `Split` splits _on_ an element. For more background, see [my comment in issue #394](https://github.com/morelinq/MoreLINQ/issues/394#issuecomment-367718432).

You might also be interested in [`GroupAdjacent`](https://morelinq.github.io/3.3/ref/api/html/Overload_MoreLinq_MoreEnumerable_GroupAdjacent.htm) assuming you want to partition or group on consecutive/adjacent runs of a key that is the item itself:

```c#
string s = "111122";
var partitions = s.GroupAdjacent(ch => ch);
```

**Comment by atifaziz** [comment] 2020-04-09 16:13
Closed as this is not a bug in `Split`.

**Closed by atifaziz** 2020-04-09 16:13 UTC
