### ISSUE TITLE
MaxOrDefault/MinOrDefault

### ISSUE THREAD

**Issue by MkazemAkhgary** [morelinq/MoreLINQ#387] opened 2018-02-17 12:20 UTC
please add this methods. its annoying, you put bizzilion linq methods, but these two methods are still missing :(

```
int max = source.MaxOrDefault(s => s.Length, 0);
```

**Comment by MkazemAkhgary** [comment] 2018-02-17 12:40
here is basic implementation.

        public static TElement MaxOrDefault<TSource, TElement>(IEnumerable<TSource> source, Func<TSource, TElement> selector, TElement defaultValue = default, IComparer<TElement> comparer = null)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (selector == null) throw new ArgumentNullException(nameof(selector));
            if (comparer == null) comparer = Comparer<TElement>.Default;

            TElement maxVal = default;
            bool init = true;

            foreach (var item in source)
            {
                var val = selector(item);
                if (init) (maxVal, init) = (val, false);
                else if (comparer.Compare(val, maxVal) > 0) maxVal = val;
            }

            return init ? defaultValue : maxVal;
        }

**Comment by atifaziz** [comment] 2018-02-17 13:28
This is a duplicate of #28. [You've already made a comment there](https://github.com/morelinq/MoreLINQ/issues/28#issuecomment-366437944) to @fsateler; opening a duplicate of the issue doesn't help. #28 isn't locked.

**Closed by atifaziz** 2018-02-17 13:28 UTC
Labels: duplicate
