### ISSUE TITLE
[Proposal] IsAscending and IsDescending

### ISSUE THREAD

**Issue by Crossbow78** [morelinq/MoreLINQ#740] opened 2019-12-19 23:29 UTC
These functions can be expressed in terms of other MoreLinq extensions:

```csharp
        public static bool IsAscending<T>(this IEnumerable<T> list) where T : IComparable<T>
            => list.IsAscending(Comparer<T>.Default);

        public static bool IsAscending<T>(this IEnumerable<T> list, IComparer<T> customComparer)
            => list.Pairwise((x, y) => customComparer.Compare(x, y)).All(x => x <= 0);

        public static bool IsDescending<T>(this IEnumerable<T> list) where T : IComparable<T>
            => list.IsDescending(Comparer<T>.Default);

        public static bool IsDescending<T>(this IEnumerable<T> list, IComparer<T> customComparer)
            => list.Pairwise((x, y) => customComparer.Compare(x, y)).All(x => x >= 0);
```

Mathematically there's a difference between 'ascending' and 'strictly ascending', where the latter is not allowed to have any equal pairs. So it's worth considering adding separate extension methods like 'IsStrictlyAscending'.

Example NUnit tests:
```csharp
        [TestCase(new[] { 1, 1, 1, 1, 1, 1 }, ExpectedResult = true)]
        [TestCase(new[] { 1, 2, 3, 4, 5, 6 }, ExpectedResult = true)]
        [TestCase(new[] { 1, 2, 3, 3, 2, 1 }, ExpectedResult = false)]
        [TestCase(new[] { 'a', 'd', 'd', 'r' }, ExpectedResult = true)]
        [TestCase(new[] { 'u', 'r', 'r', 'n' }, ExpectedResult = false)]
        public bool IsAscending_ReturnsExpectedResult<T>(IEnumerable<T> list) where T : IComparable<T>
        {
            return list.IsAscending();
        }
```

**Comment by atifaziz** [comment] 2019-12-27 10:14
This seems like a duplicate of #532 where we came to the conclusion that these are not worth the effort and confusion they may cause outside a specific application or context.

I am closing this on the same basis as #532 but happy to reconsider in a new light.

**Closed by atifaziz** 2019-12-27 10:14 UTC
