### ISSUE TITLE
Add net47 as a targetFramework

### ISSUE THREAD

**Issue by chinwobble** [morelinq/MoreLINQ#611] opened 2019-09-28 07:10 UTC
If you create a net472 application and reference MoreLinq 3.2.0 it will also unnecessarily bring in `System.ValueTuple` even though the framework already has it.

The way nuget framework resolution works is that it will look for a target framework of the same family. In this case my net472 app is "closets" to net451 of morelinq rather than netstandard2.0 even though that is also compatible. 

See here for more details.
https://github.com/NuGet/Home/issues/5370

Can we add another net47 target without a dependency on `System.ValueTuple`
The benefit for consuming projects is that they do need to load this assembly which improve startup times.

**Comment by atifaziz** [comment] 2019-10-02 16:25
I'm closing this as a duplicate of #348. Please see the discussion there.

> The benefit for consuming projects is that they do need to load this assembly which improve startup times.

Do you have any number to share on the difference it makes in the start-up time?

**Closed by atifaziz** 2019-10-02 16:26 UTC
Labels: duplicate
