### ISSUE TITLE
[Proposal] WhereNotNull & SelectNotNull

### ISSUE THREAD

**Issue by bram209** [morelinq/MoreLINQ#784] opened 2021-01-05 18:23 UTC
With C# 8 nullability feature it would be nice to be able to easily filter out null values.
I always use 
```xml
        <Nullable>enable</Nullable>
        <WarningsAsErrors>nullable</WarningsAsErrors>
```
For strict nullability warnings. Would be nice if we can have linq extensions that can automatically remove all null values and return a sequence of a non-nullable type.

```csharp
     public static IEnumerable<T> WhereNotNull<T>(this IEnumerable<T?> enumerable) =>
            enumerable.Where(e => e != null)!;
```

```csharp
    IEnumerable<Person?> nullableList = new List<Person?> { new("Foo"), null, new("Bar")};
    IEnumerable<Person> values = nullableList.WhereNotNull();
    Debug.Assert(values.Count() == 2);
```

**Comment by atifaziz** [comment] 2021-01-05 20:09
I believe that this is a duplicate of #609, where [I have presented arguments why `Choose` is what you want, better, more powerful _and_ more generic](https://github.com/morelinq/MoreLINQ/issues/609#issuecomment-525666641). In short, by breaking down the problem another way, you can use `Choose` directly:

```c#
IEnumerable<Person?> nullableList = new List<Person?> { new("Foo"), null, new("Bar")};
IEnumerable<Person> values = nullableList.Choose(Nullable.Deconstruct);
Debug.Assert(values.Count() == 2);

record Person(string Name);
    
static partial class Nullable
{
    public static (bool HasValue, T Value) Deconstruct<T>(T? nullable) =>
        nullable is not null ? (true, nullable) : default;
}
```

Notice how the signature of `Choose` also adapts correctly instead of masquerading through the [null-forgiving operator (`!`)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving). `Choose` has two type parameters: `T` and `TResult`. In the example above, `T` is `Person?` and `TResult` is `Person` and you don't need any `!` to change some `T?` into `T`.

I'll close this for now as a duplicate, but open to reconsidering if I've overlooked something.

**Closed by atifaziz** 2021-01-05 20:09 UTC

**Comment by skarllot** [comment] 2023-11-18 13:10
What you think of providing a `WhereNotNull` extension as a shortcut of using `Choose` and implementing the `Desconstruct` method?

**Comment by atifaziz** [comment] 2023-11-18 13:42
> @atifaziz What you think of providing a `WhereNotNull` extension as a shortcut of using `Choose` and

Why have another way to do the same thing?

> implementing the `Desconstruct` method?

It doesn't belong in MoreLINQ since it generally extends any type _T_ whereas this library should only be extending sequential family of types like `IEnumerable<>` & `IAsyncEnumerable<>`.

**Comment by skarllot** [comment] 2023-11-19 00:36
@atifaziz because it is a very common use case and avoid repeating the same code over and over.

And about the null forgiving, the proposed Desconstruct is masquerading the null too as it returns `default` that returns null too, but it is not detected by compiler.

**Comment by atifaziz** [comment] 2023-11-20 22:11
> @atifaziz because it is a very common use case and avoid repeating the same code over and over.

Right, but MoreLINQ is not a convenience library of small helpers for common code. See the [discussion](https://github.com/morelinq/MoreLINQ/pull/1001#pullrequestreview-1726089359) in PR #1001 for some background.

> And about the null forgiving, the proposed Desconstruct is masquerading the null too as it returns `default` that returns null too, but it is not detected by compiler.

True, but if you get a `(false, _)` then using the second half of the couple is undefined and at the risk of the user.
